unbind M-b
set -g prefix `
bind-key ` send-prefix

unbind r
bind-key r source-file ~/.config/tmux/tmux.conf

set -g mouse on
set -g mode-keys vi

set -g xterm-keys on
set -g extended-keys always
set -ag terminal-features "xterm*:extkeys:ccolour:cstyle:RGB:clipboard:focus:mouse:title"

set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1

bind b split-window -h
bind v split-window -v
unbind '"'
unbind %

bind -n M-Tab next-window
bind -n M-S-Tab previous-window
bind -n M-Space last-pane

bind-key -n M-h select-pane -R
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -L

set -g status-position top
set -g status-style bg=terminal
set -g status-justify absolute-centre
set -g status-left "[#S] #(cat /sys/class/power_supply/BAT0/capacity)%%"
set -g status-right "%D %R"
